version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - add_ssh_keys:
          fingerprints:
            - 56:83:8c:d6:67:84:cd:2d:b2:05:67:11:e8:3b:9f:21

      - run:
          name: Git Pull on Windows EC2
          command: ssh -o StrictHostKeyChecking=no -i ~/.ssh/your-private-key.pem ec2-user@your-windows-instance-ip 'cd /path/to/your/project && git pull'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
