version: 2.1
orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
            aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
            aws configure set default.region ap-south-1
      - run:
          name: Pull latest changes from Git
          command: |
            cd desktop/sangam
            git pull

workflows:
  version: 2
  build:
    jobs:
      - build
