version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Git Pull on Windows EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/windows ec2-user@ec2-3-110-83-18.ap-south-1.compute.amazonaws.com 'cd /desktop/sangam && git pull'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
