version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install sshpass
          command: sudo apt-get install -y sshpass
      - add_ssh_keys:
          fingerprints:
            - "22:6c:06:c4:c4:13:ac:59:2f:37:89:34:b5:30:6f:0f"
      - run: 
          name: Clone Git repository
          command: |
            sshpass -p ${SSH_PASS} ssh -o StrictHostKeyChecking=no Administrator@3.6.37.33 "rm -rf C:/Users/Administrator/Desktop/sangam && git clone https://github.com/sangammali/test.git C:/Users/Administrator/Desktop/sangam"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
